### PR TITLE
Move reco algorithms and related utils into their own folders

### PR DESCRIPTION
**Pull request by RaitoBezarius**
It was really confusing to work on #437 because filenames and locations didn't make a lot of sense:

- `common`: common of what?
- `algo `: what does it do? `RecommendationAlgorithm` class definition? *Wrong*, it's `common.py` which is supposed to be the common stuff between all reco algorithms.
- Where is `Dataset` definition? In `data.py` which should be `dataset.py` to be explicit. `data.py` could mean something completely different and unrelated to algorithms.

**Depends on #437.**
**Get rid of the hack in #437.**

**WARNING: ALL PICKLES MUST BE RECREATED.**

### CODE REVIEW

**Comment by jilljenn** [comment]
I don't fully get it (the advantages of the Wrapper) but I hope it will get clearer once the other PR is merged, so I can see more examples of uses of your Wrapper.

Is it possible to put algos in its whole folder, not within utils? I would enjoy `mangaki.algo` (please drop the S; it's cleaner).

**Comment by jilljenn** [comment]
Did you put `dataset` within `algo`? Is it further work? I start to think it would be interesting.

**Comment by RaitoBezarius** [comment]
@jilljenn AlgorithmWrapper is just a more powerful and cleaner `lambda: Algorithm(some_params)`.

Due to the fact that creating an ad-hoc lambda which reuse parameters from the current scope will be hard (for GC reasons and so on).

So the idea is just to make the approach more powerful, one of the biggest incoming advantages is easily modifying a parameter in an experiment.

i.e. `["xgb", ("n_estimators", 40)]` rather than having to specify parameters in the constructor order.

**Comment by RaitoBezarius** [comment]
@jilljenn Yes @ `dataset`, we discussed yesterday! :stuck_out_tongue: 
Actually, it'll remove the need of `set_parameters` and may simplify further the code (for BALSE).

**Comment by jilljenn** [comment]
I know we talked about it yesterday but sorry, I don't see it in the code.

Dataset should be saved only within algo if not anonymized, or into CSV if anonymized. We don't need dataset and algo pickles separately, it is cumbersome. (I was a bit too hard about security.)

**Comment by RaitoBezarius** [comment]
@jilljenn That's also possible, but will be done in a further PR.
Serialization is another (complex) matter, but this is a step.

**Comment by jilljenn** [comment]
I only get:

    Registered als as a recommendation algorithm
    Registered wals as a recommendation algorithm
    Registered svd as a recommendation algorithm
    Registered knn as a recommendation algorithm
    Registered zero as a recommendation algorithm
    Recommendation algorithm factory initialized. 5 algorithms available in the factory.
    Final results

As an output. What is wrong? :'(

**Comment by jilljenn** [comment]
I had to figure out by myself that I needed a configuration file.
Could you please provide a default.json? Should it be located in `data/arena_config.json`?

**Comment by jilljenn** [comment]
There is a contradiction between `@register_algorithm('svd', {'nb_components': 20})` and the actual values provided in init (`nb_components=10`). Apparently the experiment will ignore the former one.

**Comment by jilljenn** [comment]
Looks great but I have one concern.

In your PR I get:

    Evaluation of RMSE:
    [zero]: mean=1.539107 var=0.000000 std=0.000000
    => [svd-20]: mean=1.561646 var=0.000000 std=0.000000
    [knn-20]: mean=1.297895 var=0.000000 std=0.000000
    [als-10]: mean=1.150492 var=0.000000 std=0.000000

On `jj/fix-knn-in-compare` I get:

    als-20: RMSE = 1.144
    wals: RMSE = 1.179
    => svd-20: RMSE = 1.176
    knn-20: RMSE = 1.327
    zero: RMSE = 1.576

What's wrong? What happened to SVD in the meantime?

**Comment by RaitoBezarius** [comment]
Alright, makes sense, thank you for your feedback.

Let me answer in the order:

> As an output. What is wrong? :'(

I should warn and cancel the computations when the bag of algorithms is empty. You're definitely right, this is wrong :D.

> Could you please provide a default.json? Should it be located in data/arena_config.json?
Such a default is already provided under the name of `experiments/experiment.template.json`.
We can move it to `data/experiments/arena_config.json` if you wish, but I'd prefer we left it unchecked so that we don't have to worry about pushing on others different experiments. Heck, we could also collect a repository of experiment files to keep track and ease the reproducibility.

I only wish we stop the usual shuffle / comment / add / remove changeset on algorithms which happen too often and is difficult to track (except if you clone the repo and start your git magic skills, things that researchers and other curious people won't even bother to do.)

> There is a contradiction between @register_algorithm('svd', {'nb_components': 20}) and the actual values provided in init (nb_components=10). Apparently the experiment will ignore the former one.

Alright, my thinking is:

- `@register_algorithm` parameters override the default arguments of the constructor.

If that's not happening, there is a problem.

Registered algorithms will be the ones used in production (we want 20 components in production, right?). Whereas manually instantiated algorithms will be mostly used in research / notebooks / testing (we want 10 components in those cases, right?).

> Because of this, all willsee and wontsee are shrunk to zero, and MangakiZero provides better recommendations than MangakiSVD.

Oops. Makes sense. I was missing this, then.
`np.vectorize(some_function)` will return a generalization of `some_function` to operate on numpy arrays. I'll investigate, fix ASAP and provide results.

**Pull request merged**
