### PR TITLE
Kill /users route

### PR DESCRIPTION
**Pull request by RaitoBezarius**
Unreferenced route, broken route (due to Discourse not providing avatars).
Moreover, it provides an easy way to list all public users.

### CODE REVIEW

**Comment by Elarnon** [comment]
(I'll let @jilljenn decide on whether we actually want to do this or fix the avatar issue instead -- no strong feelings either way on my part)

**Comment by RaitoBezarius** [comment]
(@Elarnon In fact, according to [this plan](https://docs.google.com/document/d/1TbWJRqNjT0OSnk58oWcWBxojI6saP3Ny5PknEgDzsqk/edit#heading=h.8op73wdi5g2m) — JJ ask for this fix.)

But, you're right on the template, I'll remove it also.

**Comment by Elarnon** [comment]
https://github.com/mangaki/mangaki/blob/master/mangaki/mangaki/templates/auth/user_list.html

**Comment by Elarnon** [comment]
(`grep "Le Trio ELM"`)

**Comment by RaitoBezarius** [comment]
I'll remember this technique :D.

**Pull request merged**
