### PR TITLE
Version link to the release page.

### LINKED ISSUE #602: Version 0.6 should link to the releases page

### PR DESCRIPTION
**Pull request by FardaleM**
fix #602

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
This breaks the "development version" thing and will give less information than before, what must be done is to auto-detect when a certain version of Mangaki is in fact a release and when it's not, I think that'd be the most optimal way.

**Comment by jilljenn** [comment]
@RaitoBezarius I feel that anyway, currently the link to commit is 404, so it's better to merge the PR. Okay?

**Comment by RaitoBezarius** [comment]
I prefer for it to be 404, it's okay for now because it's a developer
feature anyway.

**Comment by jilljenn** [comment]
:/
I don't like 404 on the production website https://mangaki.fr, it's not good for SEO as well; at least let's remove the link?

**Comment by RaitoBezarius** [comment]
I'm okay on commenting the link, but no removal. It's a broken feature, not
an obsolete one I believe.

**Comment by jilljenn** [comment]
OK sorry @FardaleM !

**Pull request closed without merging**
