### PR TITLE
Prevent double logging everywhere we use a Mangaki logger

### PR DESCRIPTION
**Pull request by RaitoBezarius**
Explanation:

When you log something into a mangaki logger (i.e. in the mangaki package).

It will bubble the log record to all parents and be flushed to all handlers' of these parents.

But, `mangaki` and `` (root) as a valid parent have both a `console` handler which logs to stdout.

Thus, it'll log to console twice.

Easy fix: don't propagate once you reached Mangaki logger.

### CODE REVIEW

**Comment by Elarnon** [comment]
Why do we have INFO logging on the root logger?

**Comment by RaitoBezarius** [comment]
@Elarnon If I recall well, Sentry was not able to catch exceptions if the root logger was not set to INFO level.

**Comment by Elarnon** [comment]
This should be documented then ;)

**Comment by RaitoBezarius** [comment]
Done :).

**Comment by Elarnon** [comment]
Sentry's documentation (https://raven.readthedocs.io/en/stable/integrations/django.html) seems to say that we only need `raven.contrib.django.raven_compat` in the `INSTALLED_APPS` for the exception logging to happen. Is that incorrect? Do you have a reference for the behavior you are refering to?

**Comment by RaitoBezarius** [comment]
@Elarnon https://raven.readthedocs.io/en/stable/integrations/django.html#integration-with-logging

**Comment by Elarnon** [comment]
As far as I can tell, the configuration in your link uses a `WARNING` level for the root logger and doesn't log to the console, only to sentry?

**Comment by RaitoBezarius** [comment]
@Elarnon Right, hm, sorry for linking this without explanation.

First, I think I tried multiple approaches locally and it ended up this one working.

But you're right, we should change this to WARNING anyway.

As for the console handler, I need to check back without (my fault to not document why), but without it, it silenced some logging records for some reason (propagation I guess).

Let me check this and I will get back with more detailed answers on the why.

**Comment by Elarnon** [comment]
Thanks for looking into this! BTW while we are on the logging; is there a reason we don't directly write the following:

```python
'handlers': {
    'console': {
        'level': 'INFO',
        'class': 'logging.StreamHandler',
    },
    'sentry': {
        'level': 'ERROR',
        # When Sentry is enabled, this gets replaced by SentryHandler below
        'class': 'logging.NullHandler',
    },
}
```

and setup all the loggers/handlers by default in a single `LOGGING` definition. Then we should only have to do:

```python
if config.has_section('sentry'):
    LOGGING['handlers']['sentry']['class'] = 'raven.contrib.django.raven_compat.handlers.SentryHandler '
```

to re-root logging for the `'sentry'` handler to Sentry when it is enabled (alternatively we could set the logger to `'raven.contrib.django.raven_compat.handlers.SentryHandler'` by default and replace it with `logging.NullHandler'` if Sentry is disabled).

Unless I'm missing something, it'd make the logging configuration much more maintainable, getting rid of a bunch of dict mutations and duplicate keys to keep track of.

**Comment by RaitoBezarius** [comment]
No reason, @Elarnon — I'll do this, thanks for the tip. Didn't think about using NullHandler!

**Comment by Elarnon** [comment]
Actually now that I think about it -- we can even do something like 

```python
def get_sentry_handler(config):
    if config.has_section('sentry'):
        return 'raven.contrib.django.raven_compat.handlers.SentryHandler'
    return 'logging.NullHandler'

...
'handlers': {
    'console': {
        'level': 'INFO',
        'class': 'logging.StreamHandler',
    },
    'sentry': {
        'level': 'ERROR',
        'class': get_sentry_handler(config),
    },
}
```

which would nicely keep everything together.

**Comment by jilljenn** [comment]
Can't wait!

**Comment by RaitoBezarius** [comment]
After an investigation, I didn't figure out much more than initially, the change to INFO / + console handler on root logger has been introduced in https://github.com/mangaki/mangaki/commit/02a210751f7de7d1f6ddba8355828ac12e846182 when I found out on beta that Sentry reporting was not working.

In fact, I think there are multiple plausible explanations:

- I misbelieved that there was a problem when the report was really done in fact, so these changes are useless (considering that, AFAIK, we have no loggers which are required to write on stdout except the mangaki, Django database ones.) and I misunderstood them as fixes, it is stupid, and I am sorry.
- Deployment has failed and the state of beta was not absolutely fine (e.g. gunicorn workers not restarted) and yet again, I misunderstood there was a bug with the loggers.
- (low probability) An old bug in Raven could have caused this but I cannot find record in their issue tracker.

Also, the rationale behind moving to `INFO` and adding the console logger was for debugging purpose and see what was going wrong. As it "magically fixed" the issue, I just adopted this as fixes, which was ultimately also wrong.

@Elarnon I am sorry for the introduction of obscure stuff.

**Comment by RaitoBezarius** [comment]
Let's merge @jilljenn !

**Pull request merged**
