### PR TITLE
Remove the JS Reverse view

### PR DESCRIPTION
**Pull request by RaitoBezarius**

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
You'd have to parse the JavaScript inline'd to get access to all the routes, rather than querying a view.

But, I notice now that we didn't ask properly the question : what do we want to do with JS Reverse? Do we want to remove the view? Do we want to find a way to _not leak_ the URLs?

**Comment by Elarnon** [comment]
As pointed out offline by @ejls "leaking the URLs" is not a concern since mangaki is opensource anyways. 

I am not entirely convinced by the use of JS reverse, but I think the view version has the advantage of being cache-able and not filling every page that requires it with a bunch of mostly useless javascript (since there is at most 1-2 reversals taking place anyways).

**Comment by RaitoBezarius** [comment]
Right. Then, what would you use to ensure that the JS URLs are synchronized with the `urls.py` file?

**Comment by Elarnon** [comment]
We should have a public API whose URIs don't change :-)

But in the meantime I think that the view version is an acceptable compromise, I am less convinced by the inline version for the reasons outlined above.

**Comment by RaitoBezarius** [comment]
Agreed, let's close it and move it on #130

**Pull request closed without merging**
